[package]
name = "korangar"
version = "0.1.0"
edition = "2021"

[dependencies]
korangar_procedural = { path = "procedural" }
derive-new = "0.5"
vulkano = "0.28"
vulkano-shaders = "0.28"
vulkano-win = "0.28"
winit = "0.26"
num = "*"
cgmath = { version = "0.18", features = ["serde"] }
serde = "1.0.137"
ron = "0.7.1"
rusttype = { version = "0.9.2", features = ["gpu_cache"] }
yazi = "0.1.4"
image = "0.24.2"
pathfinding = "2.2.2"
rusqlite = "0.27.0"
chrono = "0.4"
lazy_static = { version = "1.4.0", optional = true }

[features]
debug = ["lazy_static"]
debug_network = ["debug"]
unicode = ["debug"]
colors = ["debug"]
