[package]
name = "korangar"
version = "0.1.0"

[dependencies]
korangar_procedural = { path = "procedural" }
derive-new = "0.5"
vulkano = "0.28"
vulkano-shaders = "0.28"
vulkano-win = "0.28"
winit = "0.26"
num = "*"
cgmath = { version = "0.18", features = ["serde"] }
serde = "1.0.137"
serde_json = "1.0"
png = "0.16"
bmp = "*"
pathfinding = "2.2.2"
yazi = "0.1.4"

[features]
debug = ["lazy_static", "chrono"]
debug_gamefiles = ["debug"]
debug_model = ["debug"]
debug_map = ["debug"]
unicode = []
colors = []

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.lazy_static]
version = "1.4.0"
optional = true
