[workspace]
resolver = "2"
members = ["korangar", "ragnarok_*", "korangar_*"]

[workspace.dependencies]
bitflags = "2.4.2"
cgmath = { version = "0.18", features = ["serde"] }
chrono = "0.4"
derive-new = "0.6.0"
korangar_interface = { path = "korangar_interface" }
korangar_procedural = { path = "korangar_procedural" }
korangar_debug = { path = "korangar_debug" }
num = "0.4.1"
ragnarok_bytes = { path = "ragnarok_bytes" }
ragnarok_networking = { path = "ragnarok_networking" }
ragnarok_procedural = { path = "ragnarok_procedural" }
serde = "1.0.137"
