[package]
name = "korangar"
version = "0.1.0"
edition = "2021"

[dependencies]
procedural = { path = "procedural" }
rayon = "1.5.3"
rand = "0.8.5"
derive-new = "0.5"
# Temporarily use GitHub as source until https://github.com/vulkano-rs/vulkano/pull/2075 is in a new release
vulkano = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "1d14f01" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "1d14f01" }
vulkano-win = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "1d14f01" }
bytemuck = { version = "1.7", features = ["derive", "extern_crate_std", "min_const_generics"] }
winit = "0.27"
num = "*"
cgmath = { version = "0.18", features = ["serde"] }
serde = "1.0.137"
ron = "0.7.1"
rusttype = { version = "0.9.2", features = ["gpu_cache"] }
yazi = "0.1.4"
image = "0.24.2"
pathfinding = "2.2.2"
chrono = "0.4"
lazy_static = { version = "1.4.0", optional = true }
collision = { git = "https://github.com/rustgd/collision-rs.git" }
mlua = { version = "0.8", features = ["lua51", "vendored"] }
lunify = "0.1.1"

[features]
local = []
debug = ["lazy_static"]
debug_network = ["debug"]
unicode = ["debug"]
plain = ["debug"]
