[package]
name = "korangar"
version = "0.1.0"

[dependencies]
vulkano = "0.26"
vulkano-shaders = "0.26"
vulkano-win = "0.26"
winit = "0.25"
cgmath = "0.18"
png = "0.16"
bmp = "*"
pnet = "*"

[features]
debug = ["lazy_static", "chrono"]
debug_model = ["debug"]
debug_map = ["debug"]
colors = []

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.lazy_static]
version = "1.4.0"
optional = true
