[package]
name = "korangar"
version = "0.1.0"

[dependencies]
vulkano = { git = "https://github.com/vulkano-rs/vulkano.git" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano.git" }
vulkano-win = { git = "https://github.com/vulkano-rs/vulkano.git" }
winit = "0.25"
cgmath = "0.18"
png = "0.16"
bmp = "*"

[features]
debug = ["lazy_static", "chrono", "notify"]
debug_model = ["debug"]
colors = []

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.lazy_static]
version = "1.4.0"
optional = true

[dependencies.notify]
version = "*"
optional = true
