on: [push]

name: Tests

jobs:
  check:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            #components: rustfmt, clippy

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test

concurrency:
  group: ${{ github.ref }}-tests
  cancel-in-progress: true
